patNum = 1;
partNum = 3;

file = load(sprintf('patients results/pat%d_%d_all_results_unfiltered.mat', patNum, partNum));
L_selected = file.L_XY_all;
R_selected = file.R_all;

colorbarMin = min([min(L_selected(:)), min(L_selected(:))]);
colorbarMax = max([max(L_selected(:)), max(L_selected(:))]);


eegImagescResult(file.timePointNames, file.R_all, file.numPairs, ...
 file.percentEndSeizureLocation, ...
 sprintf("R, pat %d part %d", patNum, partNum), ...
 sprintf("patients results/pat%d_%d_R_unfiltered.jpg", patNum, partNum),...
    file.selectedPairNames, colorbarMin, colorbarMax)

eegImagescResult(file.timePointNames, file.L_XY_all, file.numPairs, ...
 file.percentEndSeizureLocation, ...
 sprintf("L, pat %d part %d", patNum, partNum), ...
 sprintf("patients results/pat%d_%d_L_unfiltered.jpg", patNum, partNum),...
    file.selectedPairNames, colorbarMin, colorbarMax)

wantPair = "";
wantTimeIntervalEnd = "";
paint = true;
% plotScatterZonas(L_selected, R_selected, file.selectedPairNames, file.timePointNames, ...
%     sprintf("patients results/pat%d_%d_unfiltered_scatter.jpg", patNum, partNum), ...
%     sprintf("pat %d part %d", patNum, partNum));
plotScatter(L_selected, R_selected, file.selectedPairNames, file.timePointNames, ...
    wantPair, wantTimeIntervalEnd, paint, ...
    sprintf("patients results/pat%d_%d_unfiltered_scatter.jpg", patNum, partNum), ...
    sprintf("pat %d part %d", patNum, partNum));

% plotScatterDBSCAN(L_selected, R_selected, file.selectedPairNames);
